### ISSUE TITLE
Wnck-CRITICAL: update_client_list: assertion 'reentrancy_guard == 0' failed

### ISSUE THREAD

**Issue by gabrielfin** [ubuntu-mate/mate-window-applets#20]
This error shows up constantly on all three applets:
```
(window-buttons-applet:19310): Wnck-CRITICAL **: 17:17:54.909: update_client_list: assertion 'reentrancy_guard == 0' failed
```

It appears to come from these lines:
https://github.com/ubuntu-mate/mate-window-applets/blob/master/window-buttons-applet/window-buttons-applet.vala#L223
https://github.com/ubuntu-mate/mate-window-applets/blob/master/window-title-applet/window-title-applet.vala#L64
https://github.com/ubuntu-mate/mate-window-applets/blob/master/window-menu-applet/window-menu-applet.vala#L81

Apparently it's because that function is being called too often. 

I've commented those lines and have been using the applets for a couple of weeks and have found no issues. Is calling that function really needed?

**Comment by vkareh** [comment]
@gabrielfin - have you tested this using all three options (`active-always`, `active-maximized`, and `topmost-maximized`)? It seems like the first two do it to get the active window without having to wait for the next idle loop, and the `topmost-maximized` does it to get the list of all windows (stacked bottom to top, to get the topmost).

If this is necessary for `topmost-maximized`, then this probably needs a refactor, since calling `wnck_screen_force_update` is a painfully bad way of getting the current windows on the screen. Worst case we put this function inside the case block and deal with it later.

If it's necessary for the other two behaviors, then we should be using a different mechanism, like calling  [`XGetWindowProperty`](https://tronche.com/gui/x/xlib/window-information/XGetWindowProperty.html) for the `_NET_ACTIVE_WINDOW` atom on the root window (not sure what the x11 API looks like for vala, to be honest). Because `wnck_screen_force_update` is definitely an overkill (it updates a million different things, and then some).

Another thing we could do for the active window is to get the windows stacked, iterate over them, and check `gdk_window_get_state(w) == GDK_WINDOW_STATE_FOCUSED` or something like that. Not pretty, but still way faster than a `wnck_screen_force_update` (assuming the update is not necessary for the `get_windows_stacked`, of course).

**Comment by gabrielfin** [comment]
I've been testing it with `topmost-maximized`. I just switched to `active-always` and haven't noticed any issues either, but I'll keep an eye. In all behaviours, the window-title-applet updates immediately, but there may be edge cases...

I'm not sure I understand what `wnck_screen_force_update` is for, but according to documentation it is only needed after a `WnckScreen` is created, right? When is a `WnckScreen` created? Aren't `WnckScreen`s created far long before the applets are initialized?

**Comment by vkareh** [comment]
WnckScreen is a representation of GdkScreen, which are created way before any of this loads. The update happens automatically, non-forced, whenever a window changes, so there's rarely a good reason to call the `force_update`. As for its purpose, it literally updates the internal list of all windows across all workspaces and viewports, then re-creates the entire list of windows in stacked order, along with every window property or hint. It's a costly operation, and could lead to recursive calculations (which is why it has a guard (the `reentrancy_guard`) to make sure that the function is not being called in a circular fashion).

So if this works well without it, I'd suggest sending a pull request and get more people testing it to make sure there are no weird edge cases with it.

**Comment by gabrielfin** [comment]
That's what I suspected. Thanks. I've opened a PR.
